### ISSUE TITLE
Config File Not Generated

### ISSUE THREAD

**Issue by Nibby0** [TheExploration/Name-Spoofer#1]
Upon setting custom text for the first time, the game lag spikes. All further changes do not lag the game. Nothing is created in the config folder and no changes are saved on reboot. It also gives an error message every time anything is changed, although all changes still work. Using MultiMC, Java version 1.8.0_311, latest Forge version, Win 10.

https://pastebin.com/bzHeRsMR

I've tried:
Reinstalling
Using a fresh instance
Marking the file as safe in Windows

**Comment by TheExploration** [comment]
is this forge 1.8.9? and also have you tried the normal launcher?

**Comment by TheExploration** [comment]
also what error message does it say every time anything is changed

**Comment by philsarisk** [comment]
oops I forgot to create file in the code.

**Comment by philsarisk** [comment]
Download the new release it is working now and has been fixed. (there is a bit of lag on the first command u type in this new verison because it has to create the file)
