### ISSUE TITLE
Mod Doesn't Work On Latest Patcher

### ISSUE THREAD

**Issue by crzsujak** [TheExploration/Name-Spoofer#4]
Name-Spoofer stopped working if Patcher 1.8.6 or 1.8.7 installed. If launched without Patcher, the mod works fine. I wonder if there's a solution to make it work with newer Patcher.

**Comment by philsarisk** [comment]
Yeah I will try to fix it but I might not be able to

**Comment by redefault** [comment]
This [mod](https://github.com/ForBai/RenderTools) has a working name hider/spoofer whatever u call it this is their nickhider [module](https://github.com/ForBai/RenderTools/blob/main/src/main/java/me/anemoi/rendertools/mixin/entity/MixinFontRenderer.java)

**Comment by philsarisk** [comment]
> This [mod](https://github.com/ForBai/RenderTools) has a working name hider/spoofer whatever u call it this is their nickhider [module](https://github.com/ForBai/RenderTools/blob/main/src/main/java/me/anemoi/rendertools/mixin/entity/MixinFontRenderer.java)

u mean it works with latest patcher?

**Comment by redefault** [comment]
yep

**Comment by Tsuzuito** [comment]
For the latest versions of the patcher you need to turn off "Optimized font renderer" in the performance tab

**Comment by redefault** [comment]
oo thanks.

**Comment by philsarisk** [comment]
> For the latest versions of the patcher you need to turn off "Optimized font renderer" in the performance tab

I will include that in the description thanks for commenting
